export const GET_BOOKS_DATA = 'GET_BOOKS_DATA';
export const GET_BOOKS_DATA_SUCCESS = 'GET_BOOKS_DATA_SUCCESS';
export const GET_BOOKS_DATA_FAILURE = 'GET_BOOKS_DATA_FAILURE';

export const ADD_NEW_BOOK = 'ADD_NEW_BOOK';

export const EDIT_BOOK = 'EDIT_BOOK';
